### ISSUE TITLE
Exported enum instance not guaranteed

### ISSUE THREAD

**Issue by neovov** [deezer/KustomExport#13]
Hi,

Feel free to rename this issue so it is clearer for you 😉 .

With this Kotlin enum:
```kt
@KustomExport
public enum class Bar() {
    FIRST, SECOND
}
```

And this TypeScript code:
```ts
const bar = fooInstance.bar // Bar_FIRST
if (bar === Bar_FIRST) {
  console.log('First');
}
```
The enum instance returned on `fooInstance` is not guaranteed to be an exported instance of `Bar` (for example in this case there will be no `console.log`).

(Hi @glureau 👋 )

**Comment by glureau** [comment]
Fixed by https://github.com/deezer/KustomExport/commit/76f458435a53586d9a24ccdcefc4b351e4db39bf
Available in 0.2.0
