### ISSUE TITLE
Support mixing @JsExport and @KustomExport 

### ISSUE THREAD

**Issue by glureau** [deezer/KustomExport#17]
Kotlin 1.6.20 brings the support of enum, so using @JsExport on simple enums could be good for performance. Right now the processor expects that all dependencies are also annotated with @KustomExport, but it doesn't check if the classes actually use it or not, leading to project not able to build.

Goal is to scan the dependencies annotations and be able to support JS Export automatically.

**Comment by andylamax** [comment]
Showing a presence on how dire this feature is required

**Comment by glureau** [comment]
Work is in progress, but support of this with multi-module will unfortunately not be available with KSP 1.6.20-1.0.4 (hoping for 1.0.5) due to this limitation: https://github.com/google/ksp/issues/831 (for mono-module project you can have a preview on the branch `mixing_annotations`.)

(Previously the compiler was assuming all was annotated KustomExport, but now it needs to resolve types and annotations to ensure if it's a Kustom or Js (or nothing) export. This issue makes it impossible to know if a class from another module has been annotated or not.)
